/// Deploy WormBrain to BSC mainnet (the fully on-chain living brain).
/// Uses native ethers v6 provider+wallet to stay immune to the public-RPC
/// to:"" parsing bug. Reads the canonical connectome blob + initial state from
/// worm/data/brain_weights.json (generated by worm/brain_spec.py).
/// The private key is only read from contracts/.env and never printed.
///
/// Usage: node scripts/deploy_brain.js
const fs = require("fs");
const path = require("path");
const { ethers } = require("ethers");
require("dotenv").config({ path: path.join(__dirname, "..", ".env") });

const RPC = process.env.BSC_RPC_URL || "https://bsc-dataseed1.bnbchain.org";
const EXPECTED_CHAIN_ID = 56n; // mainnet; deliberately no testnet fallback here

async function main() {
  const pk = process.env.DEPLOYER_PRIVATE_KEY;
  if (!pk) throw new Error("DEPLOYER_PRIVATE_KEY is not set");
  const normalized = pk.startsWith("0x") ? pk : "0x" + pk;

  const W = JSON.parse(
    fs.readFileSync(path.join(__dirname, "..", "..", "worm", "data", "brain_weights.json"), "utf-8")
  );
  if (!W.blob.startsWith("0x")) throw new Error("brain_weights.json blob must be 0x-prefixed hex");
  const blobBytes = (W.blob.length - 2) / 2;
  if (W.nNeurons !== 302 || W.nEdges * 8 !== blobBytes) {
    throw new Error("brain_weights.json looks inconsistent");
  }

  const art = JSON.parse(
    fs.readFileSync(
      path.join(__dirname, "..", "artifacts", "contracts", "WormBrain.sol", "WormBrain.json"),
      "utf-8"
    )
  );

  const provider = new ethers.JsonRpcProvider(RPC, undefined, { staticNetwork: true });
  const net = await provider.getNetwork();
  if (net.chainId !== EXPECTED_CHAIN_ID) {
    throw new Error(`refusing to deploy: connected chain is ${net.chainId}, expected BSC mainnet 56`);
  }
  const wallet = new ethers.Wallet(normalized, provider);
  console.log("Deployer account:", wallet.address);

  const bal = await provider.getBalance(wallet.address);
  const gasPrice = (await provider.getFeeData()).gasPrice;
  console.log("Balance:", ethers.formatEther(bal), "BNB | gasPrice:", ethers.formatUnits(gasPrice, "gwei"), "gwei");

  const g = W.groups;
  const genesis = {
    blob: W.blob, v: W.init.V,
    attr: g.SENSORS_ATTR, oli: g.SENSORS_OLI, avert: g.SENSORS_AVERT,
    fwd: g.MOTOR_FWD, ava: g.INTER_AVA, avb: g.INTER_AVB, turn: g.TURN_IN,
    awcl: g.AWCL, awcr: g.AWCR, awal: g.AWAL, awar: g.AWAR,
    px: W.init.px, py: W.init.py, hx: W.init.hx, hy: W.init.hy,
  };

  const factory = new ethers.ContractFactory(art.abi, art.bytecode, wallet);

  // Estimate first so we can abort loudly instead of burning a failed tx.
  // Two-phase genesis: BSC mainnet enforces EIP-3860 (initcode <= 49152B) and the
  // 41KB connectome blob would not fit in the deploy payload, so we deploy an
  // (almost) empty contract first, then seed() loads the genome in its own tx.
  const est = await factory.getDeployTransaction();
  let gasLimit;
  try {
    gasLimit = await provider.estimateGas({ data: est.data, from: wallet.address });
    gasLimit = (gasLimit * 13n) / 10n; // 30% headroom
  } catch (e) {
    gasLimit = 6_000_000n; // fall back to a generous cap if eth_estimateGas is unavailable
    console.log("estimateGas unavailable (", e.shortMessage || e.message, "), using", gasLimit.toString());
  }
  const maxCost = gasLimit * gasPrice;
  console.log("deploy gasLimit:", gasLimit.toString(), "| worst-case cost:", ethers.formatEther(maxCost), "BNB");
  if (maxCost >= bal) throw new Error("insufficient balance for worst-case deployment cost");

  console.log("Deploying WormBrain (empty constructor) ...");
  const contract = await factory.deploy({ gasLimit });
  const rc = await contract.deploymentTransaction().wait();
  const addr = await contract.getAddress();
  console.log("\nWormBrain deployed:", addr);
  console.log("tx:", rc.hash, "status:", rc.status, "gasUsed:", rc.gasUsed.toString());

  console.log("Seeding genome (blob + initial state, one-shot tx) ...");
  const seedTx = await contract.seed(genesis);
  const seedRc = await seedTx.wait();
  console.log("seed tx:", seedRc.hash, "status:", seedRc.status, "gasUsed:", seedRc.gasUsed.toString());
  if (seedRc.status !== 1) throw new Error("seed tx reverted");

  // Read-back sanity: connRoot must equal keccak256 of our blob.
  const connRoot = await contract.connRoot();
  const expectedRoot = ethers.keccak256(W.blob);
  console.log("connRoot:", connRoot, connRoot === expectedRoot ? "[OK] matches local blob" : "[MISMATCH]");
  if (connRoot !== expectedRoot) throw new Error("connRoot mismatch, something is very wrong");

  // Record it next to the other mainnet deployments.
  const recPath = path.join(__dirname, "..", "deployed_addresses.json");
  const rec = JSON.parse(fs.readFileSync(recPath, "utf-8"));
  rec.WormBrain = {
    address: addr,
    txHash: rc.hash,
    blockNumber: rc.blockNumber,
    gasUsed: Number(rc.gasUsed),
    seedTxHash: seedRc.hash,
    seedGasUsed: Number(seedRc.gasUsed),
    connRoot,
  };
  fs.writeFileSync(recPath, JSON.stringify(rec, null, 2));
  console.log("deployed_addresses.json updated");

  console.log("\nNext steps:");
  console.log(`  node scripts/verify_brain.js        # BscScan source verification`);
  console.log(`  python ..\\worm\\node\\brain_daemon.py --beats 2   # feed the first on-chain steps`);
}

main().catch((e) => { console.error(e.message || e); process.exitCode = 1; });
